name: Upload Resume to Reactive Resume

on:
  push:
    branches:
      - main
    paths:
      - "data/resume.json" # only triggers when resume changes
      - .github/workflows/reactive_resume.yml # also trigger when workflow file changes, for testing purposes

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import resume to Reactive Resume
        run: |
          curl --request POST \
            --url https://rxresu.me/api/openapi/resumes/import \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.REACTIVE_RESUME_API_KEY }}" \
            -d "{\"data\": $(cat data/resume.json)}" \
            --fail \
            --silent \
            --show-error
